#!/usr/bin/env python3
"""Create a reproducibility manifest with hashes for paper artifacts."""
from __future__ import annotations

import hashlib
import json
import logging
import os
import re
import subprocess
import sys
from pathlib import Path

_log = logging.getLogger(__name__)


RESULTS_DIR = Path(__file__).resolve().parent.parent / "results"
OUT = RESULTS_DIR / "artifact_manifest.json"
_REPO_ROOT = RESULTS_DIR.parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from mvp.simulation.analysis.recovery_provenance import (  # noqa: E402
    recovery_context_from_environment,
)


# Only files regenerated by the submission pipeline are publication
# artifacts. The repository historically retained many superseded figures and
# diagnostics in results/, so recursively manifesting the whole directory
# could silently attribute an old file to a new run.
_CANONICAL_TOP_LEVEL = {
    "benchmark_summary.json", "benchmark_significance.json",
    "h2_directional_evidence.csv",
    "table1_summary.csv", "table2_ablation.csv",
    "secondary_ablation_analysis.json", "secondary_ablation_analysis.csv",
    "channel_attribution_aggregate.json",
    "channel_complementarity_test.json",
    "channel_saturation_analysis.json", "explainability_metrics.json",
    "stress_summary.json", "stress_degradation.csv",
    "stress_passfail.csv", "stress_h3_test.json",
    "paper_benchmark_table.json",
    "publication_environment.json",
    "forecast_validation_summary.json",
    "forecast_validation_predictions.csv",
    "publication_validation_receipt.json",
    "figure_provenance.json",
    "heatwave.png", "heatwave.pdf",
    "overproduction.png", "overproduction.pdf",
    "cyber_outage.png", "cyber_outage.pdf",
    "adaptive_pricing.png", "adaptive_pricing.pdf",
    "cross_scenario.png", "cross_scenario.pdf",
    "ablation.png", "ablation.pdf",
    "transport_emissions.png", "transport_emissions.pdf",
    "performance_efficiency.png", "performance_efficiency.pdf",
    "context_value.png", "context_value.pdf",
    "stress_robustness.png", "stress_robustness.pdf",
}


def _is_canonical_path(
    rel: str,
    include_raw: bool,
    run_tag: str,
    include_recovery: bool = False,
) -> bool:
    """Return whether a result path belongs to this publication run."""
    parts = Path(rel).parts
    if len(parts) == 1:
        return rel in _CANONICAL_TOP_LEVEL
    if not include_raw:
        return False
    # Canonical staged seed envelopes used by aggregation/figure rendering.
    if len(parts) == 2 and parts[0] == "benchmark_seeds":
        return parts[1].startswith("seed_") and parts[1].endswith(".json")
    # Immutable submission/DAG receipt created by hpc_run.sh after all three
    # Slurm job IDs are known. Only the receipt for this exact run is evidence.
    if len(parts) == 2 and parts[0] == "core_submission_receipts":
        return bool(run_tag) and parts[1] == f"{run_tag}.json"
    # A deterministic publication recovery is independently authorized and
    # bound to an immutable inventory of the preserved stochastic outputs.
    # These two records are admitted only for an explicitly validated
    # recovery build; their mere presence must not change a fresh-run
    # manifest's inventory.
    if len(parts) == 2 and parts[0] in {
        "publication_recovery_receipts",
        "preserved_raw_manifests",
    }:
        return (
            include_recovery
            and bool(run_tag)
            and parts[1] == f"{run_tag}.json"
        )
    # Consolidated per-seed ledgers used for channel attribution.
    if len(parts) == 4 and parts[0] == "decision_ledger_per_seed":
        return (
            bool(run_tag) and parts[1] == run_tag
            and parts[2].startswith("seed_") and parts[3].endswith(".jsonl")
        )
    # Exact retained H3 stressed-arm ledgers: five scenarios x five stressors
    # x twenty seeds, with the nominal references remaining in the primary
    # ledger tree above rather than duplicated here.
    if len(parts) == 6 and parts[0] == "decision_ledger_h3":
        return (
            bool(run_tag) and parts[1] == run_tag
            and parts[2] in {
                "heatwave", "overproduction", "cyber_outage",
                "adaptive_pricing", "baseline",
            }
            and parts[3] in {
                "sensor_noise", "missing_data", "telemetry_delay",
                "mcp_fault_injection", "compounded",
            }
            and parts[4].startswith("seed_")
            and parts[5] == f"agribrain__{parts[2]}.jsonl"
        )
    # Raw stress tasks are retained only for the run being published.
    if len(parts) >= 4 and parts[0] == "stress_runs":
        return bool(run_tag) and parts[1] == run_tag
    return False


def _sha256(path: Path) -> str:
    """Return the SHA-256 of the literal bytes stored at *path*.

    A publication archive is a byte-preservation object.  Normalizing line
    endings before hashing can make a manifest appear valid even when the
    archived payload bytes differ from the recorded digest.  The primary
    digest therefore always covers the exact bytes; any cross-platform text
    normalization belongs in an explicitly named supplemental field.
    """
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _gitignored_set(repo_root: Path, results_dir: Path) -> set[str]:
    """Return manifest-relative POSIX paths under ``results_dir`` that
    git considers ignored.

    The manifest builder must NOT include gitignored files: those files
    do not exist on a fresh CI checkout, which forces the verifier to
    treat them as "missing" -- a soft warning under ``--allow-missing``
    but a noisy one (~190 lines of WARN spam per manifest verify) that
    obscures real failures. Filtering them at manifest-construction
    time keeps the published manifest as a clean inventory of artifacts
    a fresh clone actually has on disk.

    Implementation: shell out once to ``git check-ignore --stdin``
    feeding it every candidate path, capturing the subset git reports
    as ignored. If ``git`` is not on PATH (e.g. HPC slurm worker
    without git in the venv), returns an empty set and the builder
    falls back to its pre-2026-05 behaviour (include everything,
    accept the 190 warns).
    """
    import shutil
    import subprocess
    if shutil.which("git") is None:
        return set()
    # Enumerate every file under results_dir as a manifest-relative
    # POSIX path. Walking happens once and is reused below.
    candidates: list[str] = []
    for p in results_dir.rglob("*"):
        if p.is_file():
            candidates.append(p.relative_to(results_dir).as_posix())
    if not candidates:
        return set()
    # Pass repo-relative paths to git check-ignore so it resolves them
    # against .gitignore from the repo root rather than the cwd.
    repo_rel_prefix = (
        results_dir.resolve().relative_to(repo_root.resolve()).as_posix()
    )
    payload = "\n".join(
        f"{repo_rel_prefix}/{c}" for c in candidates
    ).encode("utf-8")
    try:
        proc = subprocess.run(
            ["git", "check-ignore", "--stdin", "--no-index"],
            input=payload,
            capture_output=True,
            cwd=str(repo_root),
            check=False,
        )
    except OSError:
        return set()
    # check-ignore exits 0 when at least one match, 1 when no match,
    # 128 on other errors. Treat 128 as "give up, include everything".
    if proc.returncode == 128:
        return set()
    ignored_raw = proc.stdout.decode("utf-8", errors="replace").splitlines()
    ignored = set()
    for line in ignored_raw:
        line = line.strip()
        if not line:
            continue
        # Strip the repo-relative prefix to get back to manifest-relative.
        if line.startswith(repo_rel_prefix + "/"):
            ignored.add(line[len(repo_rel_prefix) + 1:])
    return ignored


def main() -> None:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    include = []
    include_raw = os.environ.get("ARTIFACT_MANIFEST_INCLUDE_RAW", "0") == "1"
    run_tag = os.environ.get("ARTIFACT_RUN_TAG", "").strip()
    repo_root = RESULTS_DIR.parents[2]
    recovery_provenance = recovery_context_from_environment(
        results_dir=RESULTS_DIR,
        repo_root=repo_root,
    )
    include_recovery = recovery_provenance is not None
    if include_raw and not run_tag:
        raise RuntimeError(
            "ARTIFACT_MANIFEST_INCLUDE_RAW=1 requires ARTIFACT_RUN_TAG so "
            "raw artifacts from older runs cannot enter the manifest."
        )
    if include_recovery and not include_raw:
        raise RuntimeError(
            "deterministic recovery requires ARTIFACT_MANIFEST_INCLUDE_RAW=1 "
            "so the preserved-input provenance records are manifested"
        )
    # Resolve the repo root so the gitignore probe can run with cwd at
    # the repo top rather than at results/ (where .gitignore is not
    # the canonical authority for partial paths).
    ignored_set = set() if include_raw else _gitignored_set(repo_root, RESULTS_DIR)
    # Recursive glob so the manifest also covers per-seed dumps
    # (benchmark_seeds/*/seed_*.json) and per-step audit-trail
    # ledgers (decision_ledger/*.jsonl). The earlier non-recursive
    # ``RESULTS_DIR.glob("*")`` skipped both subdirectories
    # entirely, so verify_manifest.py --strict-commit could not
    # detect tampering of the per-seed evidence the manuscript
    # cites. Filter out hidden files and any files inside
    # ``__pycache__`` regardless of nesting depth.
    for p in sorted(RESULTS_DIR.rglob("*")):
        if not p.is_file():
            continue
        # Skip dotfiles (.gitkeep etc.) and any path component that
        # starts with "." (covers .ipynb_checkpoints / .pytest_cache).
        if any(part.startswith(".") for part in p.relative_to(RESULTS_DIR).parts):
            continue
        if "__pycache__" in p.parts:
            continue
        # Skip transient local-only directories that should never end
        # up in the published manifest:
        #   - ``preview/``: downsized PNG previews generated for
        #     UI/IDE display; gitignored, never committed, and would
        #     cause spurious manifest-mismatch errors when CI tries
        #     to verify against a fresh checkout that lacks them.
        #   - ``decision_ledger_per_seed/`` and ``decision_ledger_h2/``:
        #     the large (~300 MB+) regenerable per-seed decision ledgers.
        #     The git check-ignore probe above already excludes them, but
        #     it no-ops on an HPC worker without git on PATH; skipping by
        #     path here keeps the published manifest lean regardless of
        #     the build environment.
        _parts = p.relative_to(RESULTS_DIR).parts
        always_transient = {"preview"}
        raw_only = {
            "decision_ledger_per_seed", "decision_ledger_h2",
            "decision_ledger_h3",
        }
        if _parts and (
            _parts[0] in always_transient
            or (_parts[0] in raw_only and not include_raw)
        ):
            continue
        # Manifest path is the relative POSIX path so the JSON is
        # platform-stable (Windows backslashes never reach the
        # serialized output). The verify_manifest.py reader joins
        # this against RESULTS_DIR using Path() which is
        # cross-platform.
        rel = p.relative_to(RESULTS_DIR).as_posix()
        if not _is_canonical_path(
            rel, include_raw, run_tag, include_recovery=include_recovery,
        ):
            continue
        # Skip gitignored files: see _gitignored_set docstring above.
        # The verifier already warns on these (--allow-missing); the
        # manifest builder should not have included them in the first
        # place.
        if rel in ignored_set:
            continue
        include.append(
            {
                "file": rel,
                "bytes": p.stat().st_size,
                "sha256": _sha256(p),
            }
        )
    # Resolution order for the manifest's git_commit:
    #   1. AGRIBRAIN_GIT_COMMIT env var (HPC pipelines export this so the
    #      manifest stamp survives slurm contexts where git is not in PATH);
    #   2. git rev-parse HEAD subprocess (the local-dev path);
    #   3. "unknown" sentinel (last-resort fallback; verify_manifest.py
    #      with --strict-commit will reject this, by design).
    #
    # Reproducibility hardening (post-2026-04 audit fix):
    #   - When the env-var override is supplied, we cross-check it against
    #     ``git rev-parse HEAD`` (when git is available) and reject the
    #     stamping if they disagree. A user could otherwise export an old
    #     SHA (deliberately or accidentally) and the manifest would record
    #     a commit that does not match the working tree the simulator
    #     actually ran on.
    #   - When the working tree is dirty (``git status --porcelain``
    #     non-empty), we record ``dirty=True`` and append "+dirty" to the
    #     stamped commit so verify_manifest.py --strict-commit (which
    #     rejects non-clean commits by default) catches the mismatch.
    #     This prevents the silent "the run matches commit X" claim being
    #     true-modulo-uncommitted-changes which is the canonical
    #     non-reproducible-stamping failure mode.
    #   - ``AGRIBRAIN_ALLOW_DIRTY=1`` overrides the dirty rejection for
    #     contexts where the user has explicitly accepted the dirty stamp
    #     (e.g. local exploratory runs where reproducibility is not the
    #     goal). The override still appends "+dirty" to the SHA so the
    #     resulting manifest is honestly labeled.
    git_root = str(RESULTS_DIR.parent.parent.parent)
    head_sha = ""
    is_dirty = False
    git_available = True
    try:
        head_sha = (
            subprocess.check_output(
                ["git", "rev-parse", "HEAD"], cwd=git_root,
                stderr=subprocess.PIPE,
            ).decode("utf-8").strip()
        )
    except Exception:
        git_available = False
    # Tier 3 fallback (post-2026-05): direct read of ``.git/HEAD``.
    # On HPC slurm workers ``git`` is often not on PATH; the env-var
    # path may also be missing if a manual sbatch bypasses the
    # orchestrator's --export propagation. Reading .git/HEAD directly
    # uses only the shared filesystem and the Python stdlib, so the
    # manifest gets a real SHA even on a stripped-down compute node.
    # Mirrors the same fallback added to aggregate_seeds.py in
    # commit 8154d67. If the read succeeds, head_sha is set and
    # git_available stays its tier-2 value (unchanged), so the
    # downstream env-var-equality check still functions correctly.
    if not head_sha:
        try:
            head_path = RESULTS_DIR.parent.parent.parent / ".git" / "HEAD"
            head_text = head_path.read_text(encoding="utf-8").strip()
            if head_text.startswith("ref: "):
                ref = head_text[5:].strip()
                ref_path = RESULTS_DIR.parent.parent.parent / ".git" / ref
                if ref_path.exists():
                    candidate = ref_path.read_text(encoding="utf-8").strip()
                    if len(candidate) == 40 and all(
                        c in "0123456789abcdef" for c in candidate
                    ):
                        head_sha = candidate
                else:
                    # Packed refs fallback.
                    packed = RESULTS_DIR.parent.parent.parent / ".git" / "packed-refs"
                    if packed.exists():
                        for line in packed.read_text(encoding="utf-8").splitlines():
                            if line.endswith(ref) and len(line) >= 41:
                                candidate = line.split(" ", 1)[0].strip()
                                if len(candidate) == 40:
                                    head_sha = candidate
                                    break
            elif len(head_text) == 40 and all(
                c in "0123456789abcdef" for c in head_text
            ):
                head_sha = head_text
        except Exception:
            pass
    try:
        if git_available:
            # Decode without .strip(): a whole-output strip eats
            # the leading status-column space of the FIRST porcelain
            # line (entries like " M path" become "M path" after
            # the strip), which then makes the column-offset parser
            # below mis-read the path field. The downstream
            # "mvp/simulation/results/" prefix filter then fails to
            # match the first alphabetical results file
            # (artifact_manifest.json) and the dirty check
            # spuriously fires on every HPC re-stamp.
            porcelain = subprocess.check_output(
                ["git", "status", "--porcelain"], cwd=git_root,
                stderr=subprocess.PIPE,
            ).decode("utf-8")
            # Filter out changes inside ``mvp/simulation/results/``
            # before deciding "dirty". The HPC pipeline regenerates
            # every figure / CSV / JSON in that directory by design,
            # so those paths are EXPECTED to differ from their
            # committed versions at manifest-build time. The
            # dirty-tree refusal exists to catch uncommitted CODE
            # changes (which would silently break the
            # commit-SHA-stamps-the-actual-code reproducibility
            # guarantee), not run-artifact regeneration. Without
            # this filter, the manifest builder would have refused
            # every HPC run because the post-aggregation tree
            # always carries modified figures/tables relative to
            # the committed snapshot.
            non_artifact_lines = []
            for raw_line in porcelain.splitlines():
                if not raw_line.strip():
                    continue
                # Whitespace-tolerant parse: the (1-or-2 char)
                # status field is whitespace-separated from the path
                # field, regardless of whether the leading column is
                # a space (unstaged-only entry) or a status letter
                # (staged entry). Robust to porcelain v1 quirks the
                # column-offset parser previously assumed away.
                # Rename pairs ("R  old -> new") still get the
                # right-hand path via the " -> " split below.
                parts = raw_line.split(None, 1)
                path = parts[1] if len(parts) >= 2 else ""
                if " -> " in path:
                    path = path.split(" -> ", 1)[1].strip()
                if path.startswith("mvp/simulation/results/"):
                    continue
                non_artifact_lines.append(raw_line)
            is_dirty = bool(non_artifact_lines)
    except Exception:
        # If status fails, assume dirty to avoid stamping a falsely-clean
        # SHA — better to fail loud than silent.
        is_dirty = True

    declared_commit = os.environ.get("AGRIBRAIN_GIT_COMMIT", "").strip()
    if (
        recovery_provenance is None
        and declared_commit
        and head_sha
        and declared_commit != head_sha
    ):
        raise RuntimeError(
            f"exported publication commit ({declared_commit!r}) does not match "
            f"the working tree's HEAD ({head_sha!r})"
        )

    if recovery_provenance is not None:
        commit = str(recovery_provenance["simulation_source_commit"])
        publication_commit = str(
            recovery_provenance["publication_code_commit"]
        )
    elif declared_commit:
        commit = declared_commit
        publication_commit = commit
    elif head_sha:
        commit = head_sha
        publication_commit = commit
    else:
        _log.warning(
            "build_artifact_manifest: git rev-parse HEAD failed and "
            "AGRIBRAIN_GIT_COMMIT env var not set; manifest will record "
            "'unknown' which verify_manifest.py --strict-commit will "
            "reject. To fix this on HPC, export AGRIBRAIN_GIT_COMMIT="
            "$(git rev-parse HEAD) before invoking the aggregate job."
        )
        commit = "unknown"
        publication_commit = commit

    for identity_name, identity_value in (
        ("simulation source", commit),
        ("publication code", publication_commit),
    ):
        if identity_value != "unknown" and not re.fullmatch(
            r"[0-9a-f]{40}", identity_value
        ):
            raise RuntimeError(
                f"Invalid {identity_name} commit identity: {identity_value!r}"
            )

    if is_dirty:
        if recovery_provenance is not None:
            raise RuntimeError(
                "deterministic publication recovery requires the repaired "
                "publication checkout to remain clean outside run artifacts"
            )
        allow_dirty = os.environ.get("AGRIBRAIN_ALLOW_DIRTY", "").strip() == "1"
        if not allow_dirty:
            raise RuntimeError(
                "build_artifact_manifest: working tree is dirty (uncommitted "
                "changes present). Stamping the manifest now would record a "
                "commit SHA that does not capture the actual code that ran. "
                "To proceed, either commit the changes (recommended) or set "
                "AGRIBRAIN_ALLOW_DIRTY=1 to explicitly accept a dirty stamp; "
                "the latter will append '+dirty' to the SHA so reviewers can "
                "see the stamp is not reproducible."
            )
        # Honest labeling: caller has acknowledged the dirty stamp.
        commit = f"{commit}+dirty"
        publication_commit = f"{publication_commit}+dirty"

    recovery_authorization = (
        recovery_provenance["recovery_authorization"]
        if recovery_provenance is not None
        else None
    )
    if recovery_authorization is not None:
        included_by_name = {record["file"]: record for record in include}
        for path_key, hash_key in (
            ("receipt_file", "receipt_literal_sha256"),
            (
                "preserved_raw_manifest_file",
                "preserved_raw_manifest_literal_sha256",
            ),
            ("original_submission_receipt_file", None),
        ):
            name = recovery_authorization[path_key]
            record = included_by_name.get(name)
            if record is None:
                raise RuntimeError(
                    f"recovery provenance artifact is absent from manifest: {name}"
                )
            if hash_key is not None and record["sha256"] != recovery_authorization[
                hash_key
            ]:
                raise RuntimeError(
                    f"recovery provenance artifact hash changed: {name}"
                )

        final_recovery = recovery_context_from_environment(
            results_dir=RESULTS_DIR,
            repo_root=repo_root,
        )
        if final_recovery != recovery_provenance:
            raise RuntimeError(
                "publication recovery provenance changed during manifest build"
            )

    payload = {
        "schema_version": 2,
        "git_commit": commit,
        "simulation_source_commit": commit,
        "publication_code_commit": publication_commit,
        "dual_provenance": bool(commit != publication_commit),
        "recovery_authorization": recovery_authorization,
        "git_dirty": bool(is_dirty),
        "hash_semantics": {
            "sha256": "SHA-256 of literal file bytes",
            "bytes": "literal file length in bytes",
        },
        "includes_raw_run_artifacts": bool(include_raw),
        "artifact_run_tag": run_tag or None,
        "artifact_count": len(include),
        "artifacts": include,
    }
    OUT.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"Saved artifact manifest: {OUT}")


if __name__ == "__main__":
    main()
